[package]
name = "rackup"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]

[dependencies]
clap = "2.26"
indicatif = "0.8"
gpgme = "0.6"
error-chain = "0.11"
futures = "0.1.16"
futures-cpupool = "0.1.7"
zstd = "0.4.16"
